name: Fetch Cypress A11y Results

on:
  workflow_run:
    workflows: ["Run Cypress Tests"]  
    types:
      - completed

jobs:
  fetch-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Yarn dependencies
        run: yarn install

      - name: Install Cypress A11y Results API
        run: npm install --force https://cdn.cypress.io/extract-cloud-results/v1/extract-cloud-results.tgz

      - name: Fetch Accessibility Results
        run: node ./scripts/verifyAccessibilityResults.js
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
