name: My Cypress Test Suite with A11y Results API

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
        
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This is not necessary, but is more of a best practice
      - name: Install Yarn dependencies
        run: yarn install

      # This will install the Cypress A11y Results API
      - name: Install Cypress A11y Results API
        run: npm install --force https://cdn.cypress.io/extract-cloud-results/v1/extract-cloud-results.tgz
      
      - name: Verify Accessibility Results
        run: node ./scripts/verifyAccessibilityResults.js

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}