name: My Cypress Test Suite with A11y Results API

on:
  push:

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # This will install deps from your yarn.lock file  
      - name: Install Yarn dependencies
        run: yarn install

      - name: Cypress Run
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true

      - name: Wait for Results Processing
        run: sleep 2m # Wait 2 mins before running this script

      - name: Install Cypress A11y Results API
        run: npm install --force https://cdn.cypress.io/extract-cloud-results/v1/extract-cloud-results.tgz

      - name: Fetch Accessibility Results
        run: node ./scripts/verifyAccessibilityResults.js
