name: Run Cypress Tests and Fetch A11y Results

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          command: yarn cypress run --record --parallel --tag "a11y"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Wait for Results Processing
        run: sleep 2m # Wait 2 mins before runnnig this script

      - name: Install Cypress A11y Results API
        run: npm install --force https://cdn.cypress.io/extract-cloud-results/v1/extract-cloud-results.tgz

      - name: Fetch Accessibility Results
        run: node ./scripts/verifyAccessibilityResults.js
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
