name: Run Cypress Tests

on:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          record: true
          parallel: true
          command: npx cypress run --record --tag "a11y"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # RUN_TAGS: "${{ github.run_id }}"
